name: Trigger Service1 Codepipeline
on:
  push:
    paths:
      - "service1/**"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
        with:
          aws-region: "ap-southeast-1"
          aws-access-key: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
          aws-session-token: ${{ secrets.AWS_PIPELINE_SESSION_TOKEN }}
          pipeline-name: "service1-test"
