name: Trigger Service1 Codepipeline
on:
  push:
    paths:
      - "service2/**"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: configure AWS creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
       aws-region: ap-northeast-2
    - name: Start CodePipeline
      uses: moia-oss/aws-codepipeline-trigger@v1
      with:
       pipeline: service1-test
       wait: true # optional (default: false)
       follow-codebuild: true # optional (default: false)
